teams:
  - Alter-Ego
  - INRIA
  - Sorbonne Université Service Robots Team
  - DLR
  - KIT
  - GEPETTO
  - SocRob@Home
  - Voice of the Line

room_names:
  - DLR Kitchen:
    - locations:
      - DLR dishwasher:
        - placement_location: True
        - pick_location: True
      - DLR counter:
        - placement_location: True
        - pick_location: True
      - DLR drawer:
        - placement_location: True
        - pick_location: True
  - KIT Kitchen:
    - locations:
      - KIT dishwasher:
        - placement_location: True
        - pick_location: True
      - KIT counter:
        - placement_location: True
        - pick_location: True
      - KIT drawer:
        - placement_location: True
        - pick_location: True
  - INRIA Kitchen:
    - locations:
      - INRIA dishwasher:
        - placement_location: True
        - pick_location: True
      - INRIA cabinet:
        - placement_location: True
        - pick_location: True
      - INRIA drawer:
        - placement_location: True
        - pick_location: True
      - INRIA counter:
        - placement_location: True
        - pick_location: True
      - table:
        - placement_location: True
        - pick_location: True



objects:
  - cleaning_supplies:
    - category: cleaning_supply
    - items:
      - glass_cleanser
      - bleach_cleanser
      - hygiene_spray
      - toothpaste
  - dishes:
    - category: dish
    - items:
      - bowl
      - plate
      - mug
  - food:
    - category: food
    - items:
      - cracker_box
      - sugar
      - chocolate_jello
      - strawberry_jello
      - spam
      - coffee
      - pringles
      - mustard
      - tomato_soup
      - blue_salt
      - yellow_salt
      - green_salt
      - mashed_potatoes
      - rusk
      - amicelli
      - raviolli
      - powdered_sugar
      - nutella_go
      - cereals
      - chocolate_bars
  - fruits:
    - category: fruit
    - items:
      - banana
      - strawberry
      - apple
      - lemon
      - peach
      - pear
      - orange
      - plum
  - toys:
    - category: toy
    - items:
      - soccer_ball
      - soft_ball
      - baseball
      - tennis_ball
      - racquetball
      - rubiks_cube
