teams:
  - University of Seville
  - IIT
  - RSL


room_names:
  - Main Hall:
    - locations:
      - PickUp Point A:
        - placement_location: False
        - pick_location: True
      - Delivery Point A:
        - placement_location: True
        - pick_location: False
      - PickUp Point B:
        - placement_location: False
        - pick_location: True
      - Delivery Point B:
        - placement_location: True
        - pick_location: False
      - PickUp Point C:
        - placement_location: False
        - pick_location: True
      - Delivery Point C:
        - placement_location: True
        - pick_location: False
      - Delivery Point D:
        - placement_location: True
        - pick_location: False
      - Delivery Point E:
        - placement_location: True
        - pick_location: False
      - PickUp Point F:
        - placement_location: False
        - pick_location: True
      - PickUp Point G:
        - placement_location: False
        - pick_location: True
  - Entrance Hall:
    - locations:
      - PickUp Point C:
        - placement_location: False
        - pick_location: False
      - Delivery Point D:
        - placement_location: False
        - pick_location: False


objects:
  - parcels:
    - category: parcel
    - items:
      - parcel A1
      - parcel A2
      - parcel A3
      - parcel A4
      - parcel A5